volumes:
  mongo:
    driver: local
  geoserver_data:  # Volume per mantenere i dati di GeoServer
  postgis_data:

services:
  mongo:
    image: mongo:5.0
    restart: always
    command: --nojournal
    ports:
      - 27027:27017
    volumes:
      - mongo:/data/db

  geodata-be:
    image: geodata-be:main
    container_name: "geodata-be"
    build:
      context: .
    depends_on:
      - mongo
      - postgis
    restart: always
    ports:
      - '9090:9090'
    environment:
      - SERVER_PORT=9090
      - SERVER_URL=https://geocacher-api-dev.urbreath.tech
      - HOST_ORION=https://orion-dev.urbreath.tech
      - HOST_NGSIBROKER=https://ngsi-broker-dev.urbreath.tech
      - MONGODB_URL=mongodb://mongo
      - PLATFORM=dev #prod
      - GEOSERVER_URL=http://geoserver-dev.urbreath.tech/geoserver
      - POSTGRES_URL=jdbc:postgresql://postgis:5432/ProvaPostGIS
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - APP_CITIES=Aarhus,Athens,Cluj-Napoca,Kajaani,Leuven,Madrid,Parma,Pilsen,Tallinn

  postgis:
    image: postgis/postgis:15-3.3
    container_name: postgis
    restart: always
    environment:
      POSTGRES_DB: ProvaPostGIS
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data