server.port=9090
mongodb.url=mongodb://localhost:27017
mongodb.database=interface
HOST_ORION=https://orion.dev.ecosystem-urbanage.eu
# HOST_ORION=http://orion:1026
PLATFORM=dev
MONGODB_URL=mongodb://localhost:27017
HOST_NGSIBROKER=https://ngsi-broker.dev.ecosystem-urbanage.eu
SERVER_URL=https://geodata-extractor.dev.ecosystem-urbanage.eu
GEOSERVER_URL=${GEOSERVER_URL}

# PostgreSQL + PostGIS Configuration
spring.datasource.url=jdbc:postgresql://postgis:5432/ProvaPostGIS
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# List of cities to check for filters
app.cities=Aarhus,Athens,Cluj-Napoca,Kajaani,Leuven,Madrid,Parma,Pilsen,Tallinn

# Keycloak configuration
keycloak.auth-server-url=${KEYCLOAK_URL}
keycloak.realm=${KEYCLOAK_REALM}
keycloak.resource=${KEYCLOAK_CLIENT_ID}
keycloak.credentials.secret=${KEYCLOAK_CLIENT_SECRET}
keycloak.redirect-uri=${KEYCLOAK_REDIRECT_URI}
