server.port=9090
mongodb.url=mongodb://localhost:27017
mongodb.database=interface
HOST_ORION=https://orion.dev.ecosystem-urbanage.eu
PLATFORM=dev
MONGODB_URL=mongodb://localhost:27017
HOST_NGSIBROKER=https://ngsi-broker.dev.ecosystem-urbanage.eu
SERVER_URL=https://geodata-extractor.dev.ecosystem-urbanage.eu
GEOSERVER_URL=${GEOSERVER_URL}
# Configurazione PostgreSQL + PostGIS
spring.datasource.url=jdbc:postgresql://postgis:5432/ProvaPostGIS
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
spring.jpa.hibernate.ddl-auto=none


